### ISSUE TITLE
Unittests failed

### ISSUE THREAD

**Issue by kellegra** [nbcrrolls/SEEKR#11]
Hi there, 

I am trying to set up the SEEKR suite. When it's coming to run the unittests I am not able to pass the tests for milestones.py and tranfsormations.py. 

I created a conda environment with (running on Scientific Linux 7.7):
python 2.7.17
numpy 1.16.6
scipy 1.2.1
mdanalysis 0.20.1

Could there be a problem with the used versions? Which versions should definitely work with the SEEKR suite? 

Here is what I obtain for milestones.py and transformations.py, respectively: 

milestones.py (same for test_generate_concentric_spheres_atom and *_atom_with_rotation):
> ERROR: test_generate_concentric_spheres (__main__.Test_milestones)
>
> Traceback (most recent call last):
>   File "milestones.py", line 639, in test_generate_concentric_spheres
>     test_milestones = generate_concentric_spheres(10.0, 0, 0, 0, 1, 1, 1, 2.0, 1, 1, False, r_low=2.0)
>   File "milestones.py", line 224, in generate_concentric_spheres
>     milestone = Milestone(anchor=anchor, dimensions=dimensions, index=i, siteid=siteid, absolute=absolute, center_type='coord')
>   File "milestones.py", line 70, in __init__
>     self.sitenum= int(re.split('(\d+)',siteid)[1])
>   File "/home/path/.conda/envs/py2717/lib/python2.7/re.py", line 171, in split
>     return _compile(pattern, flags).split(string, maxsplit)
> TypeError: expected string or buffer

transformations.py:
The expected and got arrays seem to differ only in their spacing characters (?). 

> File "transformations.py", line 901, in __main__.affine_matrix_from_points
> Failed example:
>     affine_matrix_from_points(v0, v1)
> Expected:
>     array([[   0.14549,    0.00062,  675.50008],
>            [   0.00048,    0.14094,   53.24971],
>            [   0.     ,    0.     ,    1.     ]])
> Got:
>     array([[  0.14549,   0.00062, 675.50008],
>            [  0.00048,   0.14094,  53.24971],
>            [  0.     ,   0.     ,   1.     ]])
> **********************************************************************
> File "transformations.py", line 609, in __main__.clip_matrix
> Failed example:
>     numpy.dot(M, [frustrum[1], frustrum[3], frustrum[5], 1])
> Expected:
>     array([ 1.,  1.,  1.,  1.])
> Got:
>     array([1., 1., 1., 1.])
> **********************************************************************
> File "transformations.py", line 1405, in __main__.quaternion_imag
> Failed example:
>     quaternion_imag([3, 0, 1, 2])
> Expected:
>     array([ 0.,  1.,  2.])
> Got:
>     array([0., 1., 2.])
> **********************************************************************
> 3 items had failures:
>    1 of  13 in __main__.affine_matrix_from_points
>    1 of  12 in __main__.clip_matrix
>    1 of   1 in __main__.quaternion_imag
> ***Test Failed*** 3 failures.

I hope there is anybody out there who coul point me to the right direction. 

Best regards,
Gerald

**Comment by brjagger** [comment]
Hi Gerald,

Looks like this might be an issue with my unit test, not the version. I’ll take a look and get back to you shortly!

Best,
Ben

On Feb 17, 2020, at 1:22 AM, kellegra <notifications@github.com> wrote:

﻿

Hi there,

I am trying to set up the SEEKR suite. When it's coming to run the unittests I am not able to pass the tests for milestones.py and tranfsormations.py.

I created a conda environment with (running on Scientific Linux 7.7):
python 2.7.17
numpy 1.16.6
scipy 1.2.1
mdanalysis 0.20.1

Could there be a problem with the used versions? Which versions should definitely work with the SEEKR suite?

Here is what I obtain for milestones.py and transformations.py, respectively:

milestones.py (same for test_generate_concentric_spheres_atom and *_atom_with_rotation):

ERROR: test_generate_concentric_spheres (main.Test_milestones)

Traceback (most recent call last):
File "milestones.py", line 639, in test_generate_concentric_spheres
test_milestones = generate_concentric_spheres(10.0, 0, 0, 0, 1, 1, 1, 2.0, 1, 1, False, r_low=2.0)
File "milestones.py", line 224, in generate_concentric_spheres
milestone = Milestone(anchor=anchor, dimensions=dimensions, index=i, siteid=siteid, absolute=absolute, center_type='coord')
File "milestones.py", line 70, in init
self.sitenum= int(re.split('(\d+)',siteid)[1])
File "/home/path/.conda/envs/py2717/lib/python2.7/re.py", line 171, in split
return _compile(pattern, flags).split(string, maxsplit)
TypeError: expected string or buffer

transformations.py:
The expected and got arrays seem to differ only in their spacing characters (?).

File "transformations.py", line 901, in main.affine_matrix_from_points
Failed example:
affine_matrix_from_points(v0, v1)
Expected:
array([[ 0.14549, 0.00062, 675.50008],
[ 0.00048, 0.14094, 53.24971],
[ 0. , 0. , 1. ]])
Got:
array([[ 0.14549, 0.00062, 675.50008],
[ 0.00048, 0.14094, 53.24971],
[ 0. , 0. , 1. ]])

________________________________

File "transformations.py", line 609, in main.clip_matrix
Failed example:
numpy.dot(M, [frustrum[1], frustrum[3], frustrum[5], 1])
Expected:
array([ 1., 1., 1., 1.])
Got:
array([1., 1., 1., 1.])

________________________________

File "transformations.py", line 1405, in main.quaternion_imag
Failed example:
quaternion_imag([3, 0, 1, 2])
Expected:
array([ 0., 1., 2.])
Got:
array([0., 1., 2.])

________________________________

3 items had failures:
1 of 13 in main.affine_matrix_from_points
1 of 12 in main.clip_matrix
1 of 1 in main.quaternion_imag
Test Failed 3 failures.

I hope there is anybody out there who coul point me to the right direction.

Best regards,
Gerald

**Comment by brjagger** [comment]
Looks like this was an issue with newer versions of MDAnalysis and numpy. I've updated the unittests accordingly and tested with the following versions

python 2.7.15
Numpy 1.16.5
scipy 1.2.1
mdanalysis 0.20.1

let me know if this fixes the problem for you
